name: background_services
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_background_service: ^5.0.5
  device_info_plus: ^9.1.1
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
